Repository GiSeok-Hong/wonderart-crm, pull requests merged in 2023-12, with the labels that each got.

#90 Wonderart-CRM #89 월 단위 수업 생성 기능 개발
  prisma/schema.prisma
  src/app/api/class/route.ts
  src/service/class.ts
Labels: enhancement

#92 Wonderart-CRM #91 시간표 페이지 코드 리팩토링
  src/components/schedule/DefaultStudentList.tsx
  src/components/schedule/Schedule.tsx
Labels: refactor

#94 Wonderart-CRM #93 월별 수업 생성 시 등록 여부가 '퇴원'인 학생은 제외하도록 수정
  src/service/class.ts
Labels: bug

#97 Wonderart-CRM #86 Prisma schema 선생님 연락처 unique 설정
  prisma/schema.prisma
  src/service/teacher.ts
Labels: enhancement
